const MYWORK = Object.freeze({
  VERSION: '1.0.0-dev-pr06',

  PROPERTIES: {
    DB_SPREADSHEET_ID: 'MYWORK_DB_SPREADSHEET_ID'
  },

  SHEETS: {
    SETTINGS: '00_SETTINGS',
    USERS: '01_USERS',

    TASKS: '10_TASKS',
    TASK_RESULTS: '11_TASK_RESULTS',
    TASK_DEPENDENCIES: '12_TASK_DEPENDENCIES',

    PROJECTS: '20_PROJECTS',
    PROJECT_MILESTONES: '21_PROJECT_MILESTONES',
    PROJECT_UPDATES: '22_PROJECT_UPDATES',

    AUDIT_LOG: '90_AUDIT_LOG',
    COUNTERS: '99_COUNTERS'
  },

  TASK_STATUS: {
    NOT_STARTED: 'NOT_STARTED',
    IN_PROGRESS: 'IN_PROGRESS',
    WAITING: 'WAITING',
    ON_HOLD: 'ON_HOLD',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },

  TASK_SOURCE: {
    MANUAL: 'MANUAL',
    PROJECT: 'PROJECT'
  },

  PRIORITY: {
    HIGH: 'HIGH',
    MEDIUM: 'MEDIUM',
    LOW: 'LOW'
  },

  PROJECT_STATUS: {
    PLANNING: 'PLANNING',
    IN_PROGRESS: 'IN_PROGRESS',
    ON_HOLD: 'ON_HOLD',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },

  PROJECT_HEALTH: {
    ON_TRACK: 'ON_TRACK',
    ATTENTION: 'ATTENTION',
    AT_RISK: 'AT_RISK'
  }
});
