// Monthly workbook import. Existing historical records are immutable in this endpoint.
function monthlyOrdinal_(r){return Number(r.Year)*12+Number(r.Month);}
function monthlyPlaceholder_(r){return Number(r.Year)===2026&&Number(r.Month)>=8&&Number(r.Month)<=12&&r.Scenario==='ACTUAL'&&r.Status==='DRAFT'&&Number(r.Revision)===1&&String(r.Source||'').startsWith('TD thuc.xlsx | TD thuc!')&&['Total','Voice','SMS','Data','VAS'].every(k=>r[k]!==''&&r[k]!=null&&Number(r[k])===0);}
function monthlyEqual_(a,b){if(a==null||a==='')return b==null||b==='';if(b==null||b==='')return false;return typeof a==='number'&&typeof b==='number'?Math.abs(a-b)<=Math.max(0.000001,Math.abs(a)*1e-9):String(a)===String(b);}
function monthlyPlan_(payload,markets,existing){
 if(!payload||!Number.isInteger(payload.year)||payload.year<2000||payload.year>2100||!Number.isInteger(payload.month)||payload.month<1||payload.month>12||typeof payload.filename!=='string'||payload.filename.length>250)throw Error('Kỳ hoặc tên file không hợp lệ.');
 if(!Array.isArray(payload.consumption)||payload.consumption.length>120||!Array.isArray(payload.kpi)||payload.kpi.length!==11)throw Error('Thiếu hoặc thừa bản ghi từ hai sheet.');
 const target=payload.year*12+payload.month,expected=['VTG','VTC','STL','NAT','MOV','VTL','VTP','VTB','VTZ','MYN'],codes=markets.map(m=>String(m.ShortName).replace(/^VBD$/,'VTB')).concat(['VTG','VTT']);
 const plan={year:payload.year,month:payload.month,filename:payload.filename,newRecords:[],differences:[],unchanged:0,skipped:0},seen=new Set();
 const indexes={},latest={};for(const name of [CONSUMPTION_SHEET,VTG_CONSUMPTION_SHEET,MARKET_KPI_SHEET]){indexes[name]={};latest[name]=0;for(const r of existing[name]||[]){const key=name===MARKET_KPI_SHEET?[r.MarketCode,r.Year,r.Month].join('|'):consumptionKey_(r);if(indexes[name][key])throw Error('Trùng kỳ trong Sheet '+name);indexes[name][key]=r;if(name!==MARKET_KPI_SHEET&&(r.Scenario!=='ACTUAL'||Number(r.Month)===0||monthlyPlaceholder_(r)))continue;latest[name]=Math.max(latest[name],monthlyOrdinal_(r));}}
 const evaluate=(name,r,code,fields)=>{const key=name===MARKET_KPI_SHEET?[r.MarketCode,r.Year,r.Month].join('|'):consumptionKey_(r),id=name+'|'+key;if(seen.has(id))throw Error('Trùng bản ghi trong file.');seen.add(id);const old=indexes[name][key],ord=monthlyOrdinal_(r);if(ord===target&&ord>latest[name]&&(!old||monthlyPlaceholder_(old))){plan.newRecords.push({sheet:name,record:r,old:old||null,code});return;}
 if(old&&!monthlyPlaceholder_(old)){const a=name===MARKET_KPI_SHEET?JSON.parse(old.ValuesJSON):old,b=name===MARKET_KPI_SHEET?JSON.parse(r.ValuesJSON):r;let changes=0;for(const k of fields)if(!monthlyEqual_(a[k],b[k])){plan.differences.push({sheet:name,market:code,year:r.Year,month:r.Month,field:k,stored:a[k]??null,incoming:b[k]??null});changes++;}if(!changes)plan.unchanged++;}else plan.skipped++;};
 const periods={};for(const input of payload.consumption){const code=String(input.marketCode||'').replace(/^VBD$/,'VTB');if(!expected.includes(code)||input.year!==payload.year||!Number.isInteger(input.month)||input.month<1||input.month>payload.month||(!payload.compareOld&&input.month!==payload.month)||input.scenario!=='ACTUAL'||input.status!=='DRAFT')throw Error('Bản ghi không thuộc kỳ nhập hợp lệ.');periods[input.month]=(periods[input.month]||[]).concat(code);const group=code==='VTG',r=consumptionValidate_(input,group?[{MarketID:'VTG',ShortName:'VTG'}]:markets);if(['Total','Voice','SMS','Data','VAS'].some(k=>r[k]===''))throw Error('Thiếu chỉ tiêu tiêu dùng '+code);evaluate(group?VTG_CONSUMPTION_SHEET:CONSUMPTION_SHEET,r,code,['Total','Voice','SMS','Data','VAS']);}
 if(!periods[payload.month]||Object.values(periods).some(a=>a.length!==10||new Set(a).size!==10))throw Error('Mỗi kỳ phải có VTG và 9 thị trường.');
 const kpiCodes=[];for(const input of payload.kpi){if(input.year!==payload.year||input.month!==payload.month)throw Error('KPI không thuộc kỳ file.');const r=kpiValidate_(input,codes);kpiCodes.push(r.MarketCode);evaluate(MARKET_KPI_SHEET,r,r.MarketCode,MARKET_KPI_FIELDS);}if(expected.concat('VTT').some(c=>!kpiCodes.includes(c)))throw Error('Thiếu thị trường KPI.');
 plan.count=plan.newRecords.length;return plan;
}
function monthlyExisting_(){return {[CONSUMPTION_SHEET]:consumptionRows_(),[VTG_CONSUMPTION_SHEET]:consumptionRows_(VTG_CONSUMPTION_SHEET),[MARKET_KPI_SHEET]:getSheetObjects_(MARKET_KPI_SHEET)};}
function monthlyPublic_(plan){return {year:plan.year,month:plan.month,filename:plan.filename,count:plan.count,newRecords:plan.newRecords.map(p=>({sheet:p.sheet,market:p.code,year:p.record.Year,month:p.record.Month,placeholder:!!p.old})),differences:plan.differences,unchanged:plan.unchanged,skipped:plan.skipped};}
function apiPreviewMonthlyWorkbook(payload){ensureCurrentUser_();kpiSheet_();return monthlyPublic_(monthlyPlan_(payload,marketRead_('30_MARKETS'),monthlyExisting_()));}
function apiImportMonthlyWorkbook(payload){
 const actor=ensureCurrentUser_(),lock=LockService.getScriptLock();lock.waitLock(30000);const backups=[],limits={};let auditSafe=null;
 try{const plan=monthlyPlan_(payload,marketRead_('30_MARKETS'),monthlyExisting_());if(!plan.count)return {...monthlyPublic_(plan),saved:0};
 const op=newOperationId_(),now=new Date(),audit=[];auditSafe=getSheet_(MYWORK.SHEETS.AUDIT_LOG).getLastRow();
 for(const p of plan.newRecords){const {sheet:s,headers:h}=p.sheet===MARKET_KPI_SHEET?kpiSheet_():consumptionSheet_(p.sheet);if(limits[p.sheet]===undefined)limits[p.sheet]=s.getLastRow();let row=s.getLastRow()+1;
 if(p.old){const rows=s.getRange(2,1,s.getLastRow()-1,h.length).getValues(),i=rows.findIndex(r=>r[h.indexOf('RecordID')]===p.old.RecordID);if(i<0)throw Error('Bản ghi chờ nhập đã thay đổi.');row=i+2;backups.push({sheet:p.sheet,row,values:rows[i]});}
 const r=Object.assign(p.record,{RecordID:p.old?p.old.RecordID:'IMPORT-'+Utilities.getUuid(),Revision:p.old?Number(p.old.Revision)+1:1,UpdatedBy:actor.UserID,CreatedAt:p.old?p.old.CreatedAt:now,UpdatedAt:now});
 if(row>s.getMaxRows())s.insertRowsAfter(s.getMaxRows(),row-s.getMaxRows());s.getRange(row,1,1,h.length).setValues([objectToRow_(h,r).map(v=>typeof v==='string'&&v.startsWith('=')?"'"+v:v)]);SpreadsheetApp.flush();const actual=rowToObject_(h,s.getRange(row,1,1,h.length).getValues()[0]),a=serializeRecordForClient_(actual),b=serializeRecordForClient_(r);for(const k of h)if(!monthlyEqual_(a[k],b[k]))throw Error('Không lưu được '+p.code+' / '+k);
 audit.push({entityType:p.sheet===MARKET_KPI_SHEET?'MARKET_KPI':p.sheet===VTG_CONSUMPTION_SHEET?'VTG_CONSUMPTION':'MOBILE_CONSUMPTION',entityId:r.RecordID,action:p.old?'FILL_NEW_PERIOD':'CREATE',fieldName:'Record',oldValue:p.old||'',newValue:actual,userId:actor.UserID,operationId:op});}
 auditRecordsBatchLocked_(audit);SpreadsheetApp.flush();return {...monthlyPublic_(plan),saved:plan.count,operationId:op};
 }catch(e){backups.forEach(b=>restoreRow_(b.sheet,b.row,b.values));Object.keys(limits).forEach(name=>deleteRowsAfter_(name,limits[name]));if(auditSafe!==null)deleteRowsAfter_(MYWORK.SHEETS.AUDIT_LOG,auditSafe);throw e;}finally{lock.releaseLock();}
}
