const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const dir=path.resolve(__dirname,'..'),ctx=vm.createContext({console});
for(const f of ['Config.gs','Db.gs','AuditService.gs','ConsumptionService.gs','ConsumptionApi.gs'])vm.runInContext(fs.readFileSync(path.join(dir,f),'utf8'),ctx);
vm.runInContext("\nvar tables={},flushFailure=false,auditFailure=false,silentAudit=false,locks=0,seq=0;\nfunction sheet(name,headers){var s={rows:[headers.slice()],getLastRow:()=>s.rows.length,getLastColumn:()=>s.rows[0].length,capacity:1000,getMaxRows:()=>s.capacity,insertRowsAfter:(r,n)=>s.capacity+=n,setFrozenRows:()=>{},deleteRow:r=>s.rows.splice(r-1,1),deleteRows:(r,n)=>s.rows.splice(r-1,n),getRange:(r,c,n=1,w=1)=>({getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>(s.rows[r-1+i]||[])[c-1+j]??'')),setNumberFormat:()=>{},setFontWeight:()=>{},setValue:v=>{if(name==='90_AUDIT_LOG'&&auditFailure)throw Error('audit failed');s.rows[r-1]??=[];s.rows[r-1][c-1]=typeof v==='string'&&v.startsWith(\"'=\")?v.slice(1):v;},setValues:values=>{if(name==='90_AUDIT_LOG'&&silentAudit)return;if(r+values.length-1>s.capacity)throw Error('Grid exceeded');if(name==='90_AUDIT_LOG'&&auditFailure)throw Error('audit failed');values.forEach((row,i)=>{s.rows[r-1+i]??=[];row.forEach((v,j)=>s.rows[r-1+i][c-1+j]=v);});}})};tables[name]=s;return s;}\nvar db={getSheetByName:n=>tables[n],insertSheet:n=>sheet(n,[])};\ngetDb_=()=>db;ensureCurrentUser_=()=>({UserID:'U1'});\nvar LockService={getScriptLock:()=>({waitLock:()=>locks++,releaseLock:()=>locks--})};\nvar SpreadsheetApp={flush:()=>{if(flushFailure){flushFailure=false;throw Error('flush failed');}}};\nvar Utilities={getUuid:()=>String(++seq),formatDate:(d,tz,fmt)=>d.toISOString().slice(0,fmt==='yyyy-MM-dd'?10:19)},Session={getScriptTimeZone:()=> 'UTC'};\nnextIdLocked_=()=> 'AUD'+(++seq);newOperationId_=()=> 'OP'+(++seq);\nsheet('90_AUDIT_LOG',['AuditID','EntityType','EntityID','Action','FieldName','OldValue','NewValue','UserID','OperationID','CreatedAt']);\n",ctx);

vm.runInContext("sheet('99_COUNTERS',['Entity','Prefix','Current','Digits']).rows.push(['AUDIT','AUD',0,6]);marketRead_=()=>[{MarketID:'M1',ShortName:'VTC'},{MarketID:'M2',ShortName:'VTB'}];apiInitializeConsumption();",ctx);

vm.runInContext(fs.readFileSync(path.join(dir,'MarketKpiService.gs'),'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);let passed=0;function test(n,f){f();passed++;console.log('PASS '+n);}
run("apiInitializeMarketKpi();var input={marketCode:'VTC',year:2026,month:7,values:{sites:100,registered:2,active:1,population:10,marketShare:20,arpuActual:4,mouOutgoing:0},references:{population:'2025'},source:'source'}");
test('save and readback with audit',()=>{run('var saved=apiSaveMarketKpi([input]).records[0]');assert.equal(run('saved.Revision'),1);assert.equal(run('JSON.parse(saved.ValuesJSON).mouOutgoing'),0);assert.equal(run('apiMarketKpiHistory(saved.RecordID).length'),1);});
test('stale revision rejected',()=>assert.throws(()=>run('apiSaveMarketKpi([input])'),/changed/));
test('unknown field invalid percentage and period blocked',()=>{for(const patch of [{values:{fake:2}},{values:{marketShare:101}},{month:0},{values:{sites:1.5}},{values:{active:true}},{marketCode:'VTCM'}])assert.throws(()=>run('apiSaveMarketKpi([{...input,...'+JSON.stringify(patch)+'}])'));});
test('audit failure rolls back',()=>{run('auditFailure=true');assert.throws(()=>run('apiSaveMarketKpi([{...input,month:8}])'),/audit/);run('auditFailure=false');assert.equal(run('apiListMarketKpi().records.length'),1);assert.equal(run('locks'),0);});
test('silent audit write rolls back update',()=>{run('silentAudit=true');assert.throws(()=>run('apiSaveMarketKpi([{...input,revision:1,values:{sites:999}}])'),/Audit/);run('silentAudit=false');assert.equal(run('JSON.parse(apiListMarketKpi().records[0].ValuesJSON).sites'),100);});
test('physical blank row update and revision',()=>{run("tables['34_MARKET_KPI'].rows.push([]);apiSaveMarketKpi([{...input,month:8}]);apiSaveMarketKpi([{...input,month:8,revision:1,values:{sites:123}}]);");assert.equal(run('JSON.parse(apiListMarketKpi().records[1].ValuesJSON).sites'),123);});
for(const file of ['ConsumptionJS.html','ConsumptionGroupJS.html','MarketReportJS.html'])vm.runInContext(fs.readFileSync(path.join(dir,file),'utf8').replace(/<\/?script[^>]*>/g,''),ctx);
run("var c={year:2026,month:7,status:'ALL',kpi:apiListMarketKpi(),data:{markets:[{MarketID:'M1',ShortName:'VTC'}],records:[{MarketID:'M1',Year:2026,Month:7,Scenario:'ACTUAL',Total:100,Data:80}],vtgRecords:[]}};");
test('ratios units and zero MOU correct',()=>{const v=run("kpiValues_(c,'VTC')");assert.equal(v.networkActive,5);assert.equal(v.activePenetration,50);assert.equal(v.peoplePerSite,100000);assert.equal(v.subsPerSite,20000);assert.equal(v.arpuData,3.2);assert.equal(v.mouBoth,0);});
test('missing and zero denominator stay unavailable',()=>{assert.equal(run('kpiRatio_(null,1)'),null);assert.equal(run('kpiRatio_(1,0)'),null);assert.equal(run("kpiValues_(c,'STL').arpuData"),null);});
test('VTG not calculated as average KPI and VTT not part of child sum',()=>{assert.equal(run("kpiValues_(c,'VTG').arpuActual"),undefined);assert.equal(run("kpiColumns_().filter(x=>x==='VTG').length"),1);});
test('monthly KPI does not carry into other months',()=>assert.equal(run("kpiGet_({...c,month:6},'VTC')"),undefined));
test('source composition retained with explicit live alternative',()=>{run("var sourceC={...c,kpi:{records:[{MarketCode:'VTC',Year:2026,Month:7,ValuesJSON:JSON.stringify({originalDataShare:95,arpuActual:4})}]}};");assert.equal(run("kpiComposition_(sourceC,2026,7).VTC.Data"),95);assert.equal(run("kpiComposition_({...sourceC,compositionBasis:'LIVE'},2026,7).VTC.Data"),80);assert.equal(run("kpiValues_(sourceC,'VTC').arpuData"),3.8);});
test('original shares allow non-reconciled totals but reject invalid bounds',()=>{assert.throws(()=>run("kpiValidate_({...input,values:{originalDataShare:101}},['VTC'])"),/0–100/);assert.equal(run("JSON.parse(kpiValidate_({...input,values:{originalDataShare:95,originalVoiceShare:20}},['VTC']).ValuesJSON).originalDataShare"),95);});
console.log(passed+' Market report checks PASS');
