const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const dir=path.resolve(__dirname,'..'),ctx=vm.createContext({console});
for(const f of ['Config.gs','Db.gs','AuditService.gs','ConsumptionService.gs','ConsumptionApi.gs','MarketKpiService.gs','MonthlyImportService.gs'])vm.runInContext(fs.readFileSync(path.join(dir,f),'utf8'),ctx);
vm.runInContext("\nvar tables={},flushFailure=false,auditFailure=false,silentAudit=false,locks=0,seq=0;\nfunction sheet(name,headers){var s={rows:[headers.slice()],getLastRow:()=>s.rows.length,getLastColumn:()=>s.rows[0].length,capacity:1000,getMaxRows:()=>s.capacity,insertRowsAfter:(r,n)=>s.capacity+=n,setFrozenRows:()=>{},deleteRow:r=>s.rows.splice(r-1,1),deleteRows:(r,n)=>s.rows.splice(r-1,n),getRange:(r,c,n=1,w=1)=>({getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>(s.rows[r-1+i]||[])[c-1+j]??'')),setNumberFormat:()=>{},setFontWeight:()=>{},setValue:v=>{if(name==='90_AUDIT_LOG'&&auditFailure)throw Error('audit failed');s.rows[r-1]??=[];s.rows[r-1][c-1]=typeof v==='string'&&v.startsWith(\"'=\")?v.slice(1):v;},setValues:values=>{if(name==='90_AUDIT_LOG'&&silentAudit)return;if(r+values.length-1>s.capacity)throw Error('Grid exceeded');if(name==='90_AUDIT_LOG'&&auditFailure)throw Error('audit failed');values.forEach((row,i)=>{s.rows[r-1+i]??=[];row.forEach((v,j)=>s.rows[r-1+i][c-1+j]=v);});}})};tables[name]=s;return s;}\nvar db={getSheetByName:n=>tables[n],insertSheet:n=>sheet(n,[])};\ngetDb_=()=>db;ensureCurrentUser_=()=>({UserID:'U1'});\nvar LockService={getScriptLock:()=>({waitLock:()=>locks++,releaseLock:()=>locks--})};\nvar SpreadsheetApp={flush:()=>{if(flushFailure){flushFailure=false;throw Error('flush failed');}}};\nvar Utilities={getUuid:()=>String(++seq),formatDate:(d,tz,fmt)=>d.toISOString().slice(0,fmt==='yyyy-MM-dd'?10:19)},Session={getScriptTimeZone:()=> 'UTC'};\nnextIdLocked_=()=> 'AUD'+(++seq);newOperationId_=()=> 'OP'+(++seq);\nsheet('90_AUDIT_LOG',['AuditID','EntityType','EntityID','Action','FieldName','OldValue','NewValue','UserID','OperationID','CreatedAt']);\n",ctx);

vm.runInContext("sheet('99_COUNTERS',['Entity','Prefix','Current','Digits']).rows.push(['AUDIT','AUD',0,6]);marketRead_=()=>[{MarketID:'M1',ShortName:'VTC'},{MarketID:'M2',ShortName:'VTB'}];apiInitializeConsumption();",ctx);
let passed=0;const run=s=>vm.runInContext(s,ctx);function test(n,f){f();passed++;console.log('PASS '+n);}
run("var codes=['VTG','VTC','STL','NAT','MOV','VTL','VTP','VTB','VTZ','MYN'];marketRead_=()=>codes.filter(c=>c!=='VTG').map(c=>({MarketID:c,ShortName:c}));apiInitializeMarketKpi();var payload={year:2026,month:7,filename:'2026.07.xlsb',compareOld:false,consumption:codes.map(marketCode=>({marketCode,year:2026,month:7,scenario:'ACTUAL',inputMode:'AMOUNTS',status:'DRAFT',total:100,voice:10,sms:0,data:80,vas:10})),kpi:codes.concat('VTT').map(marketCode=>({marketCode,year:2026,month:7,values:{sites:10},references:{}}))};");
test('preview does not write',()=>{assert.equal(run('apiPreviewMonthlyWorkbook(payload).count'),21);assert.equal(run('consumptionRows_().length'),0);});
test('new period writes both sheets and VTG with audit',()=>{assert.equal(run('apiImportMonthlyWorkbook(payload).saved'),21);assert.equal(run('consumptionRows_().length'),9);assert.equal(run("getSheetObjects_('34_MARKET_KPI').length"),11);assert.equal(run("getSheetObjects_('90_AUDIT_LOG').length"),21);});
test('same file repeated is no-op',()=>{assert.equal(run('apiImportMonthlyWorkbook(payload).saved'),0);assert.equal(run("getSheetObjects_('90_AUDIT_LOG').length"),21);});
test('old differences only warn never overwrite',()=>{run('payload.consumption[1].vas=20');assert.equal(run('apiImportMonthlyWorkbook(payload).saved'),0);assert.ok(run('apiPreviewMonthlyWorkbook(payload).differences.length')>0);assert.equal(run("consumptionRows_().find(r=>r.MarketID==='VTC').VAS"),10);});
test('missing earlier period is not backfilled',()=>{run('var older=JSON.parse(JSON.stringify(payload));older.month=6;older.consumption.forEach(r=>r.month=6);older.kpi.forEach(r=>r.month=6)');assert.equal(run('apiImportMonthlyWorkbook(older).saved'),0);});
test('invalid payload across sheets prevents all writes',()=>{run('var next=JSON.parse(JSON.stringify(payload));next.month=8;next.consumption.forEach(r=>r.month=8);next.kpi.forEach(r=>r.month=8);next.kpi[0].values.sites=-1');assert.throws(()=>run('apiImportMonthlyWorkbook(next)'));assert.equal(run('consumptionRows_().length'),9);run('next.kpi[0].values.sites=10');});
test('audit failure rolls back all three sheets',()=>{run('auditFailure=true');assert.throws(()=>run('apiImportMonthlyWorkbook(next)'));run('auditFailure=false');assert.equal(run('consumptionRows_().length'),9);assert.equal(run("getSheetObjects_('33_VTG_CONSUMPTION').length"),1);assert.equal(run("getSheetObjects_('34_MARKET_KPI').length"),11);assert.equal(run('locks'),0);});
test('placeholder can be filled as new period',()=>{run("apiSaveConsumptionBatch([{marketCode:'VTC',year:2026,month:8,scenario:'ACTUAL',total:0,voice:0,sms:0,data:0,vas:0,source:'TD thuc.xlsx | TD thuc!JM22:JM26'}])");assert.equal(run('apiImportMonthlyWorkbook(next).saved'),21);assert.equal(run("consumptionRows_().find(r=>r.MarketID==='VTC'&&r.Month===8).Revision"),2);});
test('replay after successful save remains no-op',()=>assert.equal(run('apiImportMonthlyWorkbook(next).saved'),0));
console.log(passed+' Monthly import checks PASS');
