const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const dir=path.resolve(__dirname,'..'),ctx=vm.createContext({console});
for(const f of ['Config.gs','Db.gs','AuditService.gs','MarketService.gs'])vm.runInContext(fs.readFileSync(path.join(dir,f),'utf8'),ctx,{filename:f});
vm.runInContext("\nvar tables={},flushFailure=false,auditFailure=false,locks=0,seq=0;\nfunction sheet(name,headers){var s={rows:[headers.slice()],getLastRow:()=>s.rows.length,getLastColumn:()=>s.rows[0].length,setFrozenRows:()=>{},deleteRow:r=>s.rows.splice(r-1,1),deleteRows:(r,n)=>s.rows.splice(r-1,n),getRange:(r,c,n=1,w=1)=>({getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>(s.rows[r-1+i]||[])[c-1+j]??'')),setNumberFormat:()=>{},setFontWeight:()=>{},setValue:v=>{if(name==='90_AUDIT_LOG'&&auditFailure)throw Error('audit failed');s.rows[r-1]??=[];s.rows[r-1][c-1]=typeof v==='string'&&v.startsWith(\"'=\")?v.slice(1):v;},setValues:values=>{if(name==='90_AUDIT_LOG'&&auditFailure)throw Error('audit failed');values.forEach((row,i)=>{s.rows[r-1+i]??=[];row.forEach((v,j)=>s.rows[r-1+i][c-1+j]=v);});}})};tables[name]=s;return s;}\nvar db={getSheetByName:n=>tables[n],insertSheet:n=>sheet(n,[])};\ngetDb_=()=>db;ensureCurrentUser_=()=>({UserID:'U1'});\nvar LockService={getScriptLock:()=>({waitLock:()=>locks++,releaseLock:()=>locks--})};\nvar SpreadsheetApp={flush:()=>{if(flushFailure){flushFailure=false;throw Error('flush failed');}}};\nvar Utilities={getUuid:()=>String(++seq),formatDate:(d,tz,fmt)=>d.toISOString().slice(0,fmt==='yyyy-MM-dd'?10:19)},Session={getScriptTimeZone:()=> 'UTC'};\nnextIdLocked_=()=> 'AUD'+(++seq);newOperationId_=()=> 'OP'+(++seq);\nsheet('90_AUDIT_LOG',['AuditID','EntityType','EntityID','Action','FieldName','OldValue','NewValue','UserID','OperationID','CreatedAt']);\n",ctx);

const run=s=>vm.runInContext(s,ctx);let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
test('empty DB reports uninitialized without writes',()=>{assert.equal(run('apiListMarketContacts().ready'),false);assert.equal(run('Object.keys(tables).length'),1);});
test('initialize twice preserves existing sheets',()=>{run('apiInitializeMarketContacts()');run("tables['30_MARKETS'].sentinel=123");run('apiInitializeMarketContacts()');assert.equal(run("tables['30_MARKETS'].sentinel"),123);assert.equal(run('locks'),0);});
test('create market persists normalized code',()=>{run("var m=apiSaveMarket('',{country:'Mozambique',shortName:'mov',operator:'Movitel'}).market");assert.equal(run('m.ShortName'),'MOV');assert.equal(run('apiListMarketContacts().markets.length'),1);});
test('duplicate code rejected case-insensitively',()=>assert.throws(()=>run("apiSaveMarket('',{country:'Other',shortName:'mov'})"),/already exists/));
test('rate requires currency and valid date',()=>{assert.throws(()=>run("apiSaveMarket(m.MarketID,{exchangeRate:'64'})"),/required/);assert.throws(()=>run("apiSaveMarket(m.MarketID,{currency:'MZN',exchangeRate:'64',rateDate:'2026-02-30'})"),/invalid/);run("m=apiSaveMarket(m.MarketID,{currency:'MZN',exchangeRate:'64',rateDate:'2026-09-10'}).market");assert.equal(run('m.ExchangeRate'),64);assert.equal(run('m.RateDate'),'2026-09-10');});
test('invalid rates and unknown fields rejected',()=>{for(const val of ['0','-1','Infinity','bad'])assert.throws(()=>run('apiSaveMarket(m.MarketID,{exchangeRate:'+JSON.stringify(val)+'})'));assert.throws(()=>run("apiSaveMarket(m.MarketID,{unknown:'x'})"),/Unknown/);});
test('first active contact primary and retains plus/zeros',()=>{run("var a=apiSaveMarketContact('',{marketId:m.MarketID,contactName:'Alice',tel:'+258 087 961 6688',email:'alice@example.com'}).contact");assert.equal(run('a.IsPrimary'),true);assert.equal(run('a.Tel'),'+258 087 961 6688');});
test('second contact secondary retains leading zero',()=>{run("var b=apiSaveMarketContact('',{marketId:m.MarketID,contactName:'Bob',tel:'00123 45678'}).contact");assert.equal(run('b.IsPrimary'),false);assert.equal(run('b.Tel'),'00123 45678');});
test('switch primary audits both records with same operation',()=>{run("var changed=apiSaveMarketContact(b.ContactID,{isPrimary:true})");assert.equal(run('changed.contacts.filter(c=>c.IsPrimary).length'),1);assert.equal(run('changed.contacts.find(c=>c.ContactID===a.ContactID).IsPrimary'),false);assert.equal(run("getSheetObjects_('90_AUDIT_LOG').filter(l=>l.OperationID===changed.operationId&&l.FieldName==='IsPrimary').length"),2);});
test('deactivate primary promotes remaining active contact',()=>{run("apiSaveMarketContact(b.ContactID,{isActive:false})");assert.equal(run("marketFind_('31_MARKET_CONTACTS',a.ContactID).record.IsPrimary"),true);assert.equal(run("marketFind_('31_MARKET_CONTACTS',b.ContactID).record.IsPrimary"),false);});
test('inactive-only market has no primary; reactivation promotes',()=>{run("apiSaveMarketContact(a.ContactID,{isActive:false})");assert.equal(run('apiListMarketContacts().contacts.filter(c=>c.IsPrimary).length'),0);run("apiSaveMarketContact(a.ContactID,{isActive:true})");assert.equal(run("marketFind_('31_MARKET_CONTACTS',a.ContactID).record.IsPrimary"),true);});
test('contact validation missing parent bad email and move',()=>{assert.throws(()=>run("apiSaveMarketContact('',{marketId:'missing',contactName:'X'})"),/Market not found/);assert.throws(()=>run("apiSaveMarketContact(a.ContactID,{email:'bad'})"),/email/);assert.throws(()=>run("apiSaveMarketContact(a.ContactID,{marketId:'other'})"),/moved/);});
test('audit failure rolls back market update',()=>{run('auditFailure=true');assert.throws(()=>run("apiSaveMarket(m.MarketID,{country:'Wrong'})"),/audit failed/);run('auditFailure=false');assert.equal(run("marketFind_('30_MARKETS',m.MarketID).record.Country"),'Mozambique');});
test('audit failure rolls back contact insert',()=>{run('auditFailure=true');assert.throws(()=>run("apiSaveMarketContact('',{marketId:m.MarketID,contactName:'Wrong'})"),/audit failed/);run('auditFailure=false');assert.equal(run('apiListMarketContacts().contacts.length'),2);});
test('readback failure rolls back insert releases lock',()=>{run('flushFailure=true');assert.throws(()=>run("apiSaveMarket('',{country:'Test',shortName:'TT'})"),/flush failed/);assert.equal(run('apiListMarketContacts().markets.length'),1);assert.equal(run('locks'),0);});
test('literal formula text readback preserved',()=>{run("m=apiSaveMarket(m.MarketID,{note:'=1+1'}).market");assert.equal(run('m.Note'),'=1+1');});
test('missing duplicate actual header rejects before write',()=>{run("var headers=tables['30_MARKETS'].rows[0];var old=headers[1];headers[1]='Wrong'");assert.throws(()=>run("apiSaveMarket(m.MarketID,{country:'Oops'})"),/header/);run('headers[1]=old;headers.push(old)');assert.throws(()=>run('apiInitializeMarketContacts()'),/header/);run('headers.pop()');});
for(const f of fs.readdirSync(dir).filter(f=>f.endsWith('.gs')))new vm.Script(fs.readFileSync(path.join(dir,f),'utf8'),{filename:f});
for(const f of ['AppJS.html','MarketJS.html'])new vm.Script(fs.readFileSync(path.join(dir,f),'utf8').replace(/<\/?script[^>]*>/g,''),{filename:f});
console.log(passed+' Market Contacts tests PASS; all source syntax PASS');
